function init()
% inits params

format long g; % avoid scientific notation
global setting

PREFIX = '';
if exist('/cise/', 'file') % use different path for project location based on which computer we are on
  PREFIX = '/cise/homes/msnia/zproject';
 % cd('/cise/homes/msnia/zproject/neonDSR/code/matlab');
 % addpath('/cise/homes/msnia/zproject/neonDSR/code/matlab/');
else
    PREFIX = '/opt/zshare/zproject';
 % cd('/home/scidb/zproject/neonDSR/code/matlab/');
end


setting = struct(...
    'RED_INDEX', 34, ...
    'NIR_INDEX', 41, ...
    'GREEN_INDEX', 20, ...
    'BLUE_INDEX', 10, ...
    'NDVI_THRESHOLD', 0.4, ...
    'NIR_THRESHOLD', 0.33, ...
    'PREFIX', PREFIX, ...
    'FIELD_PATH', strcat(PREFIX, '/neonDSR/docs/field_trips.csv'), ...
    'SPECTRAL_LIBRARY', strcat(PREFIX, '/neonDSR/docs/spectral_library.csv'), ...
    'LIDAR_FILE', '/cise/homes/msnia/neon/lidar/lastools_heights/merge_lidar_7_8_9_10_13_14-height.las');


end